resources:
  - name: aws-cli
    type: cliConfig
    integration: aws-int

jobs:
  - name: mac_wait_for_exit_test_success
    type: runSh
    runtime:
      nodePool: u16custom
    steps:
    - TASK:
        name: mac_host_simple
        runtime:
          container: false
        script:
          - ls
    - TASK:
        name: mac_host_multi-simple
        runtime:
          container: false
        script: |
            ls
            pwd
            true
    - TASK:
        name: mac_host_multi-exit-0
        runtime:
          container: false
        script: |
            ls
            exit 0
            pwd
    - TASK:
        name: mac_host_exit-0->
        runtime:
          container: false
        script: >
            exit 0
    - TASK:
        name: mac_host_simple
        runtime:
          container: true
        script:
          - ls
    - TASK:
        name: mac_host_multi-simple
        runtime:
          container: true
        script: |
            ls
            pwd
            true
    - TASK:
        name: mac_host_multi-exit-0
        runtime:
          container: true
        script: |
            ls
            exit 0
            pwd
    - TASK:
        name: mac_host_exit-0->
        runtime:
          container: true
        script: exit 0

  - name: mac_wait_for_exit_test_fail1
    type: runSh
    runtime:
      nodePool: u16custom
    steps:
    - IN: mac_wait_for_exit_test_success
    - TASK:
        name: mac_host_exit-1
        runtime:
          container: false
        script: >
            exit 1

  - name: mac_wait_for_exit_test_fail2
    type: runSh
    runtime:
      nodePool: u16custom
      container: false
    steps:
    - IN: mac_wait_for_exit_test_success
    - TASK:
        name: mac_wrong_command
        script: sl

  - name: mac_wait_for_exit_test_fail3
    type: runSh
    runtime:
      nodePool: u16custom
      container: false
    steps:
    - IN: mac_wait_for_exit_test_success
    - TASK:
        name: mac_multi-line-fail
        script: |
            ls
            sl
            pwd

  - name: mac_wait_for_exit_test_fail4
    type: runSh
    runtime:
      nodePool: u16custom
      container: false
    steps:
    - IN: mac_wait_for_exit_test_success
    - TASK:
        name: mac_multi-line-fail
        script: exit -1
  - name: mac_wait_for_exit_test_fail5
    type: runSh
    runtime:
      nodePool: u16custom
      container: false
    steps:
    - IN: mac_wait_for_exit_test_success
    - IN: aws-cli
    - TASK:
        name: mac_multi-line-fail
        script: exit 11
