resources:
  - name: bharath-us-east-1
    type: integration
    integration: bharath-us-east-1

jobs:
  - name: run_aws_instance
    type: runSh
    steps:
      - IN: bharath-us-east-1
      - IN: pipelines_repo
        switch: off
      - TASK:
          - script: pushd $(shipctl get_resource_state "pipelines_repo") && git checkout scripts
          - script: ./startStopAwsInstances.sh
          - script: popd
