resources:
  - name: docker_cli
    type: cliConfig
    integration: docker

  - name: docker_test_img
    type: image
    integration: docker
    pointer:
      sourceName: "bharath92/test"
    seed:
      versionName: master

  - name: docker_img_test_repo
    type: gitRepo
    integration: github
    pointer:
      sourceName: bharath92/pipelines
      branch: test

jobs:
  - name: create_docker_img
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: docker_cli
        switch: off
      - IN: docker_img_test_repo
      - OUT: docker_test_img
      - TASK:
          - script: pushd $(shipctl get_resource_state "docker_img_test_repo") && git checkout test
          - script: docker build -t=bharath92/test:master .
          - script: docker push bharath92/test:master

  - name: rel
    type: runSh
    steps:
      - IN: create_docker_img
        switch: off
      - TASK:
          - script: echo "rel"

  - name: commit_to_test_branch
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
    - IN: rel
    - IN: docker_img_test_repo
      switch: off
    - TASK:
        - script: export SSH_PATH=git@github.com:bharath92/pipelines.git
        - script: pushd $(shipctl get_resource_state "docker_img_test_repo") && git checkout test
        - script: apt-get install -y uuid-runtime
        - script: touch $(uuidgen)
        - script: git add . && git commit -m "adding test file"
        - script: git remote add up $SSH_PATH
        - script: git push up test

  - name: tag_img
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
    - IN: commit_to_test_branch
    - IN: docker_cli
      switch: off
    - IN: docker_test_img
      switch: off
    - TASK:
        - script: docker pull bharath92/test:master
        - script: docker tag bharath92/test:master bharath92/test:test
        - script: docker push bharath92/test:test
